// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlayerOperate.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Com.Skw.PlayerOperate {
  public static partial class PlayerOperate
  {
    static readonly string __ServiceName = "com.skw.playerOperate.PlayerOperate";

    static readonly grpc::Marshaller<global::Com.Skw.PlayerOperate.OnePlayerOperation> __Marshaller_com_skw_playerOperate_OnePlayerOperation = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Skw.PlayerOperate.OnePlayerOperation.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Com.Skw.PlayerOperate.AllPlayerOperation> __Marshaller_com_skw_playerOperate_AllPlayerOperation = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Skw.PlayerOperate.AllPlayerOperation.Parser.ParseFrom);

    static readonly grpc::Method<global::Com.Skw.PlayerOperate.OnePlayerOperation, global::Com.Skw.PlayerOperate.AllPlayerOperation> __Method_sendAndReceiveOperation = new grpc::Method<global::Com.Skw.PlayerOperate.OnePlayerOperation, global::Com.Skw.PlayerOperate.AllPlayerOperation>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "sendAndReceiveOperation",
        __Marshaller_com_skw_playerOperate_OnePlayerOperation,
        __Marshaller_com_skw_playerOperate_AllPlayerOperation);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Com.Skw.PlayerOperate.PlayerOperateReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PlayerOperate</summary>
    public abstract partial class PlayerOperateBase
    {
      public virtual global::System.Threading.Tasks.Task sendAndReceiveOperation(grpc::IAsyncStreamReader<global::Com.Skw.PlayerOperate.OnePlayerOperation> requestStream, grpc::IServerStreamWriter<global::Com.Skw.PlayerOperate.AllPlayerOperation> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PlayerOperate</summary>
    public partial class PlayerOperateClient : grpc::ClientBase<PlayerOperateClient>
    {
      /// <summary>Creates a new client for PlayerOperate</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PlayerOperateClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PlayerOperate that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PlayerOperateClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PlayerOperateClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PlayerOperateClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Com.Skw.PlayerOperate.OnePlayerOperation, global::Com.Skw.PlayerOperate.AllPlayerOperation> sendAndReceiveOperation(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return sendAndReceiveOperation(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Com.Skw.PlayerOperate.OnePlayerOperation, global::Com.Skw.PlayerOperate.AllPlayerOperation> sendAndReceiveOperation(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_sendAndReceiveOperation, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PlayerOperateClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PlayerOperateClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PlayerOperateBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_sendAndReceiveOperation, serviceImpl.sendAndReceiveOperation).Build();
    }

  }
}
#endregion
