// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerOperate.proto

package com.skw.playerOperate;

public interface AllPlayerOperationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skw.playerOperate.AllPlayerOperation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
   */
  java.util.List<com.skw.playerOperate.OnePlayerOperation> 
      getPlayerOperationList();
  /**
   * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
   */
  com.skw.playerOperate.OnePlayerOperation getPlayerOperation(int index);
  /**
   * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
   */
  int getPlayerOperationCount();
  /**
   * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
   */
  java.util.List<? extends com.skw.playerOperate.OnePlayerOperationOrBuilder> 
      getPlayerOperationOrBuilderList();
  /**
   * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
   */
  com.skw.playerOperate.OnePlayerOperationOrBuilder getPlayerOperationOrBuilder(
      int index);
}
