// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerOperate.proto

package com.skw.playerOperate;

/**
 * Protobuf type {@code com.skw.playerOperate.AllPlayerOperation}
 */
public  final class AllPlayerOperation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.skw.playerOperate.AllPlayerOperation)
    AllPlayerOperationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AllPlayerOperation.newBuilder() to construct.
  private AllPlayerOperation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AllPlayerOperation() {
    playerOperation_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AllPlayerOperation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              playerOperation_ = new java.util.ArrayList<com.skw.playerOperate.OnePlayerOperation>();
              mutable_bitField0_ |= 0x00000001;
            }
            playerOperation_.add(
                input.readMessage(com.skw.playerOperate.OnePlayerOperation.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        playerOperation_ = java.util.Collections.unmodifiableList(playerOperation_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.skw.playerOperate.PlayerOperateOuterClass.internal_static_com_skw_playerOperate_AllPlayerOperation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.skw.playerOperate.PlayerOperateOuterClass.internal_static_com_skw_playerOperate_AllPlayerOperation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.skw.playerOperate.AllPlayerOperation.class, com.skw.playerOperate.AllPlayerOperation.Builder.class);
  }

  public static final int PLAYEROPERATION_FIELD_NUMBER = 1;
  private java.util.List<com.skw.playerOperate.OnePlayerOperation> playerOperation_;
  /**
   * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
   */
  public java.util.List<com.skw.playerOperate.OnePlayerOperation> getPlayerOperationList() {
    return playerOperation_;
  }
  /**
   * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
   */
  public java.util.List<? extends com.skw.playerOperate.OnePlayerOperationOrBuilder> 
      getPlayerOperationOrBuilderList() {
    return playerOperation_;
  }
  /**
   * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
   */
  public int getPlayerOperationCount() {
    return playerOperation_.size();
  }
  /**
   * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
   */
  public com.skw.playerOperate.OnePlayerOperation getPlayerOperation(int index) {
    return playerOperation_.get(index);
  }
  /**
   * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
   */
  public com.skw.playerOperate.OnePlayerOperationOrBuilder getPlayerOperationOrBuilder(
      int index) {
    return playerOperation_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < playerOperation_.size(); i++) {
      output.writeMessage(1, playerOperation_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < playerOperation_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, playerOperation_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.skw.playerOperate.AllPlayerOperation)) {
      return super.equals(obj);
    }
    com.skw.playerOperate.AllPlayerOperation other = (com.skw.playerOperate.AllPlayerOperation) obj;

    if (!getPlayerOperationList()
        .equals(other.getPlayerOperationList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPlayerOperationCount() > 0) {
      hash = (37 * hash) + PLAYEROPERATION_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerOperationList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.skw.playerOperate.AllPlayerOperation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skw.playerOperate.AllPlayerOperation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skw.playerOperate.AllPlayerOperation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skw.playerOperate.AllPlayerOperation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skw.playerOperate.AllPlayerOperation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skw.playerOperate.AllPlayerOperation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skw.playerOperate.AllPlayerOperation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.skw.playerOperate.AllPlayerOperation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skw.playerOperate.AllPlayerOperation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.skw.playerOperate.AllPlayerOperation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skw.playerOperate.AllPlayerOperation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.skw.playerOperate.AllPlayerOperation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.skw.playerOperate.AllPlayerOperation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.skw.playerOperate.AllPlayerOperation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.skw.playerOperate.AllPlayerOperation)
      com.skw.playerOperate.AllPlayerOperationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skw.playerOperate.PlayerOperateOuterClass.internal_static_com_skw_playerOperate_AllPlayerOperation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skw.playerOperate.PlayerOperateOuterClass.internal_static_com_skw_playerOperate_AllPlayerOperation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skw.playerOperate.AllPlayerOperation.class, com.skw.playerOperate.AllPlayerOperation.Builder.class);
    }

    // Construct using com.skw.playerOperate.AllPlayerOperation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPlayerOperationFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (playerOperationBuilder_ == null) {
        playerOperation_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        playerOperationBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.skw.playerOperate.PlayerOperateOuterClass.internal_static_com_skw_playerOperate_AllPlayerOperation_descriptor;
    }

    @java.lang.Override
    public com.skw.playerOperate.AllPlayerOperation getDefaultInstanceForType() {
      return com.skw.playerOperate.AllPlayerOperation.getDefaultInstance();
    }

    @java.lang.Override
    public com.skw.playerOperate.AllPlayerOperation build() {
      com.skw.playerOperate.AllPlayerOperation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.skw.playerOperate.AllPlayerOperation buildPartial() {
      com.skw.playerOperate.AllPlayerOperation result = new com.skw.playerOperate.AllPlayerOperation(this);
      int from_bitField0_ = bitField0_;
      if (playerOperationBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          playerOperation_ = java.util.Collections.unmodifiableList(playerOperation_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.playerOperation_ = playerOperation_;
      } else {
        result.playerOperation_ = playerOperationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.skw.playerOperate.AllPlayerOperation) {
        return mergeFrom((com.skw.playerOperate.AllPlayerOperation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.skw.playerOperate.AllPlayerOperation other) {
      if (other == com.skw.playerOperate.AllPlayerOperation.getDefaultInstance()) return this;
      if (playerOperationBuilder_ == null) {
        if (!other.playerOperation_.isEmpty()) {
          if (playerOperation_.isEmpty()) {
            playerOperation_ = other.playerOperation_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePlayerOperationIsMutable();
            playerOperation_.addAll(other.playerOperation_);
          }
          onChanged();
        }
      } else {
        if (!other.playerOperation_.isEmpty()) {
          if (playerOperationBuilder_.isEmpty()) {
            playerOperationBuilder_.dispose();
            playerOperationBuilder_ = null;
            playerOperation_ = other.playerOperation_;
            bitField0_ = (bitField0_ & ~0x00000001);
            playerOperationBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPlayerOperationFieldBuilder() : null;
          } else {
            playerOperationBuilder_.addAllMessages(other.playerOperation_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.skw.playerOperate.AllPlayerOperation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.skw.playerOperate.AllPlayerOperation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.skw.playerOperate.OnePlayerOperation> playerOperation_ =
      java.util.Collections.emptyList();
    private void ensurePlayerOperationIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        playerOperation_ = new java.util.ArrayList<com.skw.playerOperate.OnePlayerOperation>(playerOperation_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.skw.playerOperate.OnePlayerOperation, com.skw.playerOperate.OnePlayerOperation.Builder, com.skw.playerOperate.OnePlayerOperationOrBuilder> playerOperationBuilder_;

    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public java.util.List<com.skw.playerOperate.OnePlayerOperation> getPlayerOperationList() {
      if (playerOperationBuilder_ == null) {
        return java.util.Collections.unmodifiableList(playerOperation_);
      } else {
        return playerOperationBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public int getPlayerOperationCount() {
      if (playerOperationBuilder_ == null) {
        return playerOperation_.size();
      } else {
        return playerOperationBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public com.skw.playerOperate.OnePlayerOperation getPlayerOperation(int index) {
      if (playerOperationBuilder_ == null) {
        return playerOperation_.get(index);
      } else {
        return playerOperationBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public Builder setPlayerOperation(
        int index, com.skw.playerOperate.OnePlayerOperation value) {
      if (playerOperationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayerOperationIsMutable();
        playerOperation_.set(index, value);
        onChanged();
      } else {
        playerOperationBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public Builder setPlayerOperation(
        int index, com.skw.playerOperate.OnePlayerOperation.Builder builderForValue) {
      if (playerOperationBuilder_ == null) {
        ensurePlayerOperationIsMutable();
        playerOperation_.set(index, builderForValue.build());
        onChanged();
      } else {
        playerOperationBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public Builder addPlayerOperation(com.skw.playerOperate.OnePlayerOperation value) {
      if (playerOperationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayerOperationIsMutable();
        playerOperation_.add(value);
        onChanged();
      } else {
        playerOperationBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public Builder addPlayerOperation(
        int index, com.skw.playerOperate.OnePlayerOperation value) {
      if (playerOperationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayerOperationIsMutable();
        playerOperation_.add(index, value);
        onChanged();
      } else {
        playerOperationBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public Builder addPlayerOperation(
        com.skw.playerOperate.OnePlayerOperation.Builder builderForValue) {
      if (playerOperationBuilder_ == null) {
        ensurePlayerOperationIsMutable();
        playerOperation_.add(builderForValue.build());
        onChanged();
      } else {
        playerOperationBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public Builder addPlayerOperation(
        int index, com.skw.playerOperate.OnePlayerOperation.Builder builderForValue) {
      if (playerOperationBuilder_ == null) {
        ensurePlayerOperationIsMutable();
        playerOperation_.add(index, builderForValue.build());
        onChanged();
      } else {
        playerOperationBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public Builder addAllPlayerOperation(
        java.lang.Iterable<? extends com.skw.playerOperate.OnePlayerOperation> values) {
      if (playerOperationBuilder_ == null) {
        ensurePlayerOperationIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, playerOperation_);
        onChanged();
      } else {
        playerOperationBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public Builder clearPlayerOperation() {
      if (playerOperationBuilder_ == null) {
        playerOperation_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        playerOperationBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public Builder removePlayerOperation(int index) {
      if (playerOperationBuilder_ == null) {
        ensurePlayerOperationIsMutable();
        playerOperation_.remove(index);
        onChanged();
      } else {
        playerOperationBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public com.skw.playerOperate.OnePlayerOperation.Builder getPlayerOperationBuilder(
        int index) {
      return getPlayerOperationFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public com.skw.playerOperate.OnePlayerOperationOrBuilder getPlayerOperationOrBuilder(
        int index) {
      if (playerOperationBuilder_ == null) {
        return playerOperation_.get(index);  } else {
        return playerOperationBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public java.util.List<? extends com.skw.playerOperate.OnePlayerOperationOrBuilder> 
         getPlayerOperationOrBuilderList() {
      if (playerOperationBuilder_ != null) {
        return playerOperationBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(playerOperation_);
      }
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public com.skw.playerOperate.OnePlayerOperation.Builder addPlayerOperationBuilder() {
      return getPlayerOperationFieldBuilder().addBuilder(
          com.skw.playerOperate.OnePlayerOperation.getDefaultInstance());
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public com.skw.playerOperate.OnePlayerOperation.Builder addPlayerOperationBuilder(
        int index) {
      return getPlayerOperationFieldBuilder().addBuilder(
          index, com.skw.playerOperate.OnePlayerOperation.getDefaultInstance());
    }
    /**
     * <code>repeated .com.skw.playerOperate.OnePlayerOperation playerOperation = 1;</code>
     */
    public java.util.List<com.skw.playerOperate.OnePlayerOperation.Builder> 
         getPlayerOperationBuilderList() {
      return getPlayerOperationFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.skw.playerOperate.OnePlayerOperation, com.skw.playerOperate.OnePlayerOperation.Builder, com.skw.playerOperate.OnePlayerOperationOrBuilder> 
        getPlayerOperationFieldBuilder() {
      if (playerOperationBuilder_ == null) {
        playerOperationBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.skw.playerOperate.OnePlayerOperation, com.skw.playerOperate.OnePlayerOperation.Builder, com.skw.playerOperate.OnePlayerOperationOrBuilder>(
                playerOperation_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        playerOperation_ = null;
      }
      return playerOperationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.skw.playerOperate.AllPlayerOperation)
  }

  // @@protoc_insertion_point(class_scope:com.skw.playerOperate.AllPlayerOperation)
  private static final com.skw.playerOperate.AllPlayerOperation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.skw.playerOperate.AllPlayerOperation();
  }

  public static com.skw.playerOperate.AllPlayerOperation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AllPlayerOperation>
      PARSER = new com.google.protobuf.AbstractParser<AllPlayerOperation>() {
    @java.lang.Override
    public AllPlayerOperation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AllPlayerOperation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AllPlayerOperation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AllPlayerOperation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.skw.playerOperate.AllPlayerOperation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

