// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerOperate.proto

package com.skw.playerOperate;

public interface OnePlayerOperationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skw.playerOperate.OnePlayerOperation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *指明是哪个用户发送过来的操作
   * </pre>
   *
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <pre>
   *指明该用户发送该消息时所处的位置
   * </pre>
   *
   * <code>.com.skw.playerOperate.Position Position = 2;</code>
   */
  boolean hasPosition();
  /**
   * <pre>
   *指明该用户发送该消息时所处的位置
   * </pre>
   *
   * <code>.com.skw.playerOperate.Position Position = 2;</code>
   */
  com.skw.playerOperate.Position getPosition();
  /**
   * <pre>
   *指明该用户发送该消息时所处的位置
   * </pre>
   *
   * <code>.com.skw.playerOperate.Position Position = 2;</code>
   */
  com.skw.playerOperate.PositionOrBuilder getPositionOrBuilder();

  /**
   * <code>.com.skw.playerOperate.MoveParameter parameter = 3;</code>
   */
  boolean hasParameter();
  /**
   * <code>.com.skw.playerOperate.MoveParameter parameter = 3;</code>
   */
  com.skw.playerOperate.MoveParameter getParameter();
  /**
   * <code>.com.skw.playerOperate.MoveParameter parameter = 3;</code>
   */
  com.skw.playerOperate.MoveParameterOrBuilder getParameterOrBuilder();

  /**
   * <code>bool crouch = 4;</code>
   */
  boolean getCrouch();
}
