// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Audio.proto

package com.skw.protoBean;

public interface AskReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skw.protoBean.AskReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 req = 1;</code>
   */
  int getReq();
}
