// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Audio.proto

package com.skw.protoBean;

public interface OkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skw.protoBean.Ok)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ok = 1;</code>
   */
  String getOk();
  /**
   * <code>string ok = 1;</code>
   */
  com.google.protobuf.ByteString
      getOkBytes();
}
