// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerOperate.proto

package com.skw.playerOperate;

public final class PlayerOperateOuterClass {
  private PlayerOperateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skw_playerOperate_AllPlayerOperation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skw_playerOperate_AllPlayerOperation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skw_playerOperate_OnePlayerOperation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skw_playerOperate_OnePlayerOperation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skw_playerOperate_Position_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skw_playerOperate_Position_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skw_playerOperate_MoveParameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skw_playerOperate_MoveParameter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023PlayerOperate.proto\022\025com.skw.playerOpe" +
      "rate\"X\n\022AllPlayerOperation\022B\n\017playerOper" +
      "ation\030\001 \003(\0132).com.skw.playerOperate.OneP" +
      "layerOperation\"\234\001\n\022OnePlayerOperation\022\n\n" +
      "\002id\030\001 \001(\005\0221\n\010Position\030\002 \001(\0132\037.com.skw.pl" +
      "ayerOperate.Position\0227\n\tparameter\030\003 \001(\0132" +
      "$.com.skw.playerOperate.MoveParameter\022\016\n" +
      "\006crouch\030\004 \001(\010\"+\n\010Position\022\t\n\001x\030\001 \001(\005\022\t\n\001" +
      "y\030\002 \001(\005\022\t\n\001z\030\003 \001(\005\"0\n\rMoveParameter\022\t\n\001x" +
      "\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\022\t\n\001z\030\003 \001(\0052\206\001\n\rPlayerO" +
      "perate\022u\n\027sendAndReceiveOperation\022).com." +
      "skw.playerOperate.OnePlayerOperation\032).c" +
      "om.skw.playerOperate.AllPlayerOperation\"" +
      "\000(\0010\001B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_skw_playerOperate_AllPlayerOperation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_skw_playerOperate_AllPlayerOperation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skw_playerOperate_AllPlayerOperation_descriptor,
        new java.lang.String[] { "PlayerOperation", });
    internal_static_com_skw_playerOperate_OnePlayerOperation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_skw_playerOperate_OnePlayerOperation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skw_playerOperate_OnePlayerOperation_descriptor,
        new java.lang.String[] { "Id", "Position", "Parameter", "Crouch", });
    internal_static_com_skw_playerOperate_Position_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_skw_playerOperate_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skw_playerOperate_Position_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    internal_static_com_skw_playerOperate_MoveParameter_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_skw_playerOperate_MoveParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skw_playerOperate_MoveParameter_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
