// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerOperate.proto

package com.skw.playerOperate;

public interface PositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skw.playerOperate.Position)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *unity客户端里的float*1000发送到这里
   * </pre>
   *
   * <code>int32 x = 1;</code>
   */
  int getX();

  /**
   * <code>int32 y = 2;</code>
   */
  int getY();

  /**
   * <code>int32 z = 3;</code>
   */
  int getZ();
}
