// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Audio.proto

package com.skw.protoBean;

/**
 * Protobuf type {@code com.skw.protoBean.Audio}
 */
public  final class Audio extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.skw.protoBean.Audio)
    AudioOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Audio.newBuilder() to construct.
  private Audio(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Audio() {
    aMessage_ = emptyFloatList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Audio(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              aMessage_ = newFloatList();
              mutable_bitField0_ |= 0x00000001;
            }
            aMessage_.addFloat(input.readFloat());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              aMessage_ = newFloatList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              aMessage_.addFloat(input.readFloat());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        aMessage_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return AudioOuterClass.internal_static_com_skw_protoBean_Audio_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return AudioOuterClass.internal_static_com_skw_protoBean_Audio_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Audio.class, Builder.class);
  }

  public static final int A_MESSAGE_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.FloatList aMessage_;
  /**
   * <code>repeated float a_message = 1;</code>
   */
  public java.util.List<Float>
      getAMessageList() {
    return aMessage_;
  }
  /**
   * <code>repeated float a_message = 1;</code>
   */
  public int getAMessageCount() {
    return aMessage_.size();
  }
  /**
   * <code>repeated float a_message = 1;</code>
   */
  public float getAMessage(int index) {
    return aMessage_.getFloat(index);
  }
  private int aMessageMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getAMessageList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(aMessageMemoizedSerializedSize);
    }
    for (int i = 0; i < aMessage_.size(); i++) {
      output.writeFloatNoTag(aMessage_.getFloat(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      dataSize = 4 * getAMessageList().size();
      size += dataSize;
      if (!getAMessageList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      aMessageMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Audio)) {
      return super.equals(obj);
    }
    Audio other = (Audio) obj;

    if (!getAMessageList()
        .equals(other.getAMessageList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAMessageCount() > 0) {
      hash = (37 * hash) + A_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getAMessageList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Audio parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Audio parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Audio parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Audio parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Audio parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Audio parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Audio parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Audio parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Audio parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Audio parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Audio parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Audio parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Audio prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.skw.protoBean.Audio}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.skw.protoBean.Audio)
      AudioOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AudioOuterClass.internal_static_com_skw_protoBean_Audio_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AudioOuterClass.internal_static_com_skw_protoBean_Audio_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Audio.class, Builder.class);
    }

    // Construct using com.skw.protoBean.Audio.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      aMessage_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return AudioOuterClass.internal_static_com_skw_protoBean_Audio_descriptor;
    }

    @Override
    public Audio getDefaultInstanceForType() {
      return Audio.getDefaultInstance();
    }

    @Override
    public Audio build() {
      Audio result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Audio buildPartial() {
      Audio result = new Audio(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        aMessage_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.aMessage_ = aMessage_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Audio) {
        return mergeFrom((Audio)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Audio other) {
      if (other == Audio.getDefaultInstance()) return this;
      if (!other.aMessage_.isEmpty()) {
        if (aMessage_.isEmpty()) {
          aMessage_ = other.aMessage_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAMessageIsMutable();
          aMessage_.addAll(other.aMessage_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Audio parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Audio) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.FloatList aMessage_ = emptyFloatList();
    private void ensureAMessageIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        aMessage_ = mutableCopy(aMessage_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated float a_message = 1;</code>
     */
    public java.util.List<Float>
        getAMessageList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(aMessage_) : aMessage_;
    }
    /**
     * <code>repeated float a_message = 1;</code>
     */
    public int getAMessageCount() {
      return aMessage_.size();
    }
    /**
     * <code>repeated float a_message = 1;</code>
     */
    public float getAMessage(int index) {
      return aMessage_.getFloat(index);
    }
    /**
     * <code>repeated float a_message = 1;</code>
     */
    public Builder setAMessage(
        int index, float value) {
      ensureAMessageIsMutable();
      aMessage_.setFloat(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float a_message = 1;</code>
     */
    public Builder addAMessage(float value) {
      ensureAMessageIsMutable();
      aMessage_.addFloat(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float a_message = 1;</code>
     */
    public Builder addAllAMessage(
        Iterable<? extends Float> values) {
      ensureAMessageIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, aMessage_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float a_message = 1;</code>
     */
    public Builder clearAMessage() {
      aMessage_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.skw.protoBean.Audio)
  }

  // @@protoc_insertion_point(class_scope:com.skw.protoBean.Audio)
  private static final Audio DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Audio();
  }

  public static Audio getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Audio>
      PARSER = new com.google.protobuf.AbstractParser<Audio>() {
    @Override
    public Audio parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Audio(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Audio> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Audio> getParserForType() {
    return PARSER;
  }

  @Override
  public Audio getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

