// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Audio.proto

package com.skw.protoBean;

public interface AudioOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skw.protoBean.Audio)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated float a_message = 1;</code>
   */
  java.util.List<Float> getAMessageList();
  /**
   * <code>repeated float a_message = 1;</code>
   */
  int getAMessageCount();
  /**
   * <code>repeated float a_message = 1;</code>
   */
  float getAMessage(int index);
}
