// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Audio.proto

package com.skw.protoBean;

public interface SendBeanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skw.protoBean.SendBean)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 nearPlayer = 1;</code>
   */
  java.util.List<Integer> getNearPlayerList();
  /**
   * <code>repeated int32 nearPlayer = 1;</code>
   */
  int getNearPlayerCount();
  /**
   * <code>repeated int32 nearPlayer = 1;</code>
   */
  int getNearPlayer(int index);

  /**
   * <code>int32 player = 2;</code>
   */
  int getPlayer();

  /**
   * <code>.com.skw.protoBean.Audio audio = 3;</code>
   */
  boolean hasAudio();
  /**
   * <code>.com.skw.protoBean.Audio audio = 3;</code>
   */
  Audio getAudio();
  /**
   * <code>.com.skw.protoBean.Audio audio = 3;</code>
   */
  AudioOrBuilder getAudioOrBuilder();
}
