// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.skw.userBean;

public interface LoginResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skw.userBean.LoginResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 resultType = 1;</code>
   */
  int getResultType();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>string name = 3;</code>
   */
  String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
