// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.skw.userBean;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skw_userBean_UserRegisterBean_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skw_userBean_UserRegisterBean_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skw_userBean_UserLoginBean_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skw_userBean_UserLoginBean_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skw_userBean_RegisterResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skw_userBean_RegisterResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skw_userBean_LoginResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skw_userBean_LoginResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nUser.proto\022\020com.skw.userBean\"2\n\020UserRe" +
      "gisterBean\022\014\n\004name\030\001 \001(\t\022\020\n\010password\030\002 \001" +
      "(\t\"/\n\rUserLoginBean\022\014\n\004name\030\001 \001(\t\022\020\n\010pas" +
      "sword\030\002 \001(\t\">\n\016RegisterResult\022\022\n\nresultT" +
      "ype\030\001 \001(\005\022\n\n\002id\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\";\n\013L" +
      "oginResult\022\022\n\nresultType\030\001 \001(\005\022\n\n\002id\030\002 \001" +
      "(\005\022\014\n\004name\030\003 \001(\t2\257\001\n\016UserController\022R\n\010r" +
      "egister\022\".com.skw.userBean.UserRegisterB" +
      "ean\032 .com.skw.userBean.RegisterResult\"\000\022" +
      "I\n\005login\022\037.com.skw.userBean.UserLoginBea" +
      "n\032\035.com.skw.userBean.LoginResult\"\000B\002P\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_skw_userBean_UserRegisterBean_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_skw_userBean_UserRegisterBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skw_userBean_UserRegisterBean_descriptor,
        new String[] { "Name", "Password", });
    internal_static_com_skw_userBean_UserLoginBean_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_skw_userBean_UserLoginBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skw_userBean_UserLoginBean_descriptor,
        new String[] { "Name", "Password", });
    internal_static_com_skw_userBean_RegisterResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_skw_userBean_RegisterResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skw_userBean_RegisterResult_descriptor,
        new String[] { "ResultType", "Id", "Name", });
    internal_static_com_skw_userBean_LoginResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_skw_userBean_LoginResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skw_userBean_LoginResult_descriptor,
        new String[] { "ResultType", "Id", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
