// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.skw.userBean;

public interface UserLoginBeanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skw.userBean.UserLoginBean)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string password = 2;</code>
   */
  String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
